# Generated by Django 3.1.3 on 2020-12-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alert', '0003_auto_20201201_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commentary', models.CharField(max_length=300)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.gender')),
                ('type_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.type_animal')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=400)),
                ('postal_code', models.IntegerField()),
                ('host', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Housing_planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type_animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alert.type_animal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.user')),
            ],
        ),
        migrations.CreateModel(
            name='housing_animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.animal')),
                ('housing_planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.housing_planning')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.user'),
        ),
    ]
