# Generated by Django 3.1.3 on 2020-12-03 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0006_auto_20201203_1622'),
        ('housing', '0004_auto_20201202_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name'], 'verbose_name': 'Animal', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='housing_animal',
            options={'ordering': ['animal'], 'verbose_name': 'Housing_animal', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='housing_planning',
            options={'ordering': ['user'], 'verbose_name': 'Housin_planning', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='user_data',
            options={'ordering': ['user'], 'verbose_name': 'User_data', 'verbose_name_plural': ''},
        ),
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alert.color'),
            preserve_default=False,
        ),
    ]
