# Generated by Django 3.1.3 on 2020-12-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0007_auto_20201203_2011'),
        ('registration', '0001_initial'),
        ('housing', '0005_auto_20201203_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['name'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animal'},
        ),
        migrations.AlterModelOptions(
            name='housing_animal',
            options={'ordering': ['animal'], 'verbose_name': 'Housing animal', 'verbose_name_plural': 'Housing animal'},
        ),
        migrations.AlterModelOptions(
            name='housing_planning',
            options={'ordering': ['user'], 'verbose_name': 'Housing planning', 'verbose_name_plural': 'Planning des hébergements'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user_data'),
        ),
        migrations.AlterField(
            model_name='housing_planning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user_data'),
        ),
        migrations.DeleteModel(
            name='User_data',
        ),
    ]
