# Generated by Django 3.1.3 on 2021-01-08 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0006_auto_20201203_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='user',
        ),
    ]
