# Generated by Django 3.1.3 on 2021-01-08 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_remove_animal_user'),
        ('registration', '0002_auto_20210108_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='housing.animal'),
        ),
    ]
