# Generated by Django 3.1.5 on 2021-01-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20210113_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='username_field',
            field=models.CharField(default='user', max_length=300),
            preserve_default=False,
        ),
    ]
