# Generated by Django 3.1.5 on 2021-01-13 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_user_data_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='username_field',
        ),
    ]
