# Generated by Django 3.1.5 on 2021-01-14 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_remove_user_data_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='animal',
        ),
    ]
