# Generated by Django 3.1.3 on 2020-12-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0002_auto_20201125_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('commentary', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Housing_planning',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
