# Generated by Django 3.1.3 on 2020-12-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0002_auto_20201202_1613'),
        ('alert', '0004_auto_20201201_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.userdata'),
        ),
    ]
