# Generated by Django 3.1.3 on 2020-12-03 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('alert', '0006_auto_20201203_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert_user',
            options={'ordering': ['user'], 'verbose_name': 'Alert user', 'verbose_name_plural': "Les alertes d'utilisateurs"},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name'], 'verbose_name': 'Color', 'verbose_name_plural': 'Couleurs'},
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['gender'], 'verbose_name': 'Gender', 'verbose_name_plural': "Sexe de l'animal"},
        ),
        migrations.AlterModelOptions(
            name='type_alert',
            options={'ordering': ['alert'], 'verbose_name': 'Type Alert', 'verbose_name_plural': "Type d'alerte"},
        ),
        migrations.AlterModelOptions(
            name='type_animal',
            options={'ordering': ['type'], 'verbose_name': 'Type animal', 'verbose_name_plural': "Type d'animal"},
        ),
        migrations.AlterField(
            model_name='alert_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user_data'),
        ),
    ]
