# Generated by Django 3.1.5 on 2021-01-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0009_alert_user_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_user',
            name='img',
            field=models.ImageField(null=True, upload_to='media/alert_user'),
        ),
    ]
