# Generated by Django 3.1.5 on 2021-01-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0011_auto_20210112_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_user',
            name='check',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='alert_user',
            name='date',
            field=models.DateField(max_length=300),
        ),
        migrations.AlterField(
            model_name='alert_user',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
