# Generated by Django 3.1.5 on 2021-01-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0012_auto_20210114_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert_user',
            name='check',
        ),
        migrations.AlterField(
            model_name='alert_user',
            name='img',
            field=models.ImageField(default='img', upload_to=''),
            preserve_default=False,
        ),
    ]
