# Generated by Django 3.1.5 on 2021-01-14 21:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0015_auto_20210114_1555'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='alert_user',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
