# Generated by Django 3.1.5 on 2021-01-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0017_auto_20210114_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert_user',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
