# Generated by Django 3.1.5 on 2021-01-16 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0018_alert_user_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert_user',
            name='region',
        ),
    ]
